//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstWebService.ServiceReferenceAdder {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceAdder.MyWebServiceSoap")]
    public interface MyWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetNumberResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNumber", ReplyAction="*")]
        FirstWebService.ServiceReferenceAdder.GetNumberResponse GetNumber(FirstWebService.ServiceReferenceAdder.GetNumberRequest request);
        
        // CODEGEN: Generating message contract since element name AddResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        FirstWebService.ServiceReferenceAdder.AddResponse Add(FirstWebService.ServiceReferenceAdder.AddRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNumberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNumber", Namespace="http://tempuri.org/", Order=0)]
        public FirstWebService.ServiceReferenceAdder.GetNumberRequestBody Body;
        
        public GetNumberRequest() {
        }
        
        public GetNumberRequest(FirstWebService.ServiceReferenceAdder.GetNumberRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetNumberRequestBody {
        
        public GetNumberRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNumberResponse", Namespace="http://tempuri.org/", Order=0)]
        public FirstWebService.ServiceReferenceAdder.GetNumberResponseBody Body;
        
        public GetNumberResponse() {
        }
        
        public GetNumberResponse(FirstWebService.ServiceReferenceAdder.GetNumberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNumberResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetNumberResult;
        
        public GetNumberResponseBody() {
        }
        
        public GetNumberResponseBody(string GetNumberResult) {
            this.GetNumberResult = GetNumberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add", Namespace="http://tempuri.org/", Order=0)]
        public FirstWebService.ServiceReferenceAdder.AddRequestBody Body;
        
        public AddRequest() {
        }
        
        public AddRequest(FirstWebService.ServiceReferenceAdder.AddRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int firstno;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int secondno;
        
        public AddRequestBody() {
        }
        
        public AddRequestBody(int firstno, int secondno) {
            this.firstno = firstno;
            this.secondno = secondno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddResponse", Namespace="http://tempuri.org/", Order=0)]
        public FirstWebService.ServiceReferenceAdder.AddResponseBody Body;
        
        public AddResponse() {
        }
        
        public AddResponse(FirstWebService.ServiceReferenceAdder.AddResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddResult;
        
        public AddResponseBody() {
        }
        
        public AddResponseBody(string AddResult) {
            this.AddResult = AddResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MyWebServiceSoapChannel : FirstWebService.ServiceReferenceAdder.MyWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyWebServiceSoapClient : System.ServiceModel.ClientBase<FirstWebService.ServiceReferenceAdder.MyWebServiceSoap>, FirstWebService.ServiceReferenceAdder.MyWebServiceSoap {
        
        public MyWebServiceSoapClient() {
        }
        
        public MyWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FirstWebService.ServiceReferenceAdder.GetNumberResponse FirstWebService.ServiceReferenceAdder.MyWebServiceSoap.GetNumber(FirstWebService.ServiceReferenceAdder.GetNumberRequest request) {
            return base.Channel.GetNumber(request);
        }
        
        public string GetNumber() {
            FirstWebService.ServiceReferenceAdder.GetNumberRequest inValue = new FirstWebService.ServiceReferenceAdder.GetNumberRequest();
            inValue.Body = new FirstWebService.ServiceReferenceAdder.GetNumberRequestBody();
            FirstWebService.ServiceReferenceAdder.GetNumberResponse retVal = ((FirstWebService.ServiceReferenceAdder.MyWebServiceSoap)(this)).GetNumber(inValue);
            return retVal.Body.GetNumberResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FirstWebService.ServiceReferenceAdder.AddResponse FirstWebService.ServiceReferenceAdder.MyWebServiceSoap.Add(FirstWebService.ServiceReferenceAdder.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public string Add(int firstno, int secondno) {
            FirstWebService.ServiceReferenceAdder.AddRequest inValue = new FirstWebService.ServiceReferenceAdder.AddRequest();
            inValue.Body = new FirstWebService.ServiceReferenceAdder.AddRequestBody();
            inValue.Body.firstno = firstno;
            inValue.Body.secondno = secondno;
            FirstWebService.ServiceReferenceAdder.AddResponse retVal = ((FirstWebService.ServiceReferenceAdder.MyWebServiceSoap)(this)).Add(inValue);
            return retVal.Body.AddResult;
        }
    }
}
